apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadetpx4239-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadetpx4239-tenant-component
    app.kubernetes.io/part-of: loadetpx4239-tenant-app
  name: loadetpx4239-tenant-component
  namespace: loadetpx4239-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadetpx4239-tenant-component
    weight: null
status: {}
